
### fail because  illegal RegEx charachters

GET http://localhost:5657/api/yritys/?Kaupunki=Tur|Hel&page=1 HTTP/1.1

### Fail not int
GET http://localhost:5657/api/yritys/?Kaupunki=Turl&page=abc HTTP/1.1

### Fail because empty query
GET http://localhost:5657/api/yritys/? HTTP/1.1

### Unvalid schema
GET http://localhost:5657/api/yritys/?asd=2323&bcm=Elos HTTP/1.1

### Partially valid schema. Should return results
GET http://localhost:5657/api/yritys/?asd=2323&bcm=Elos&Kaupunki=Helsinki HTTP/1.1
